//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0p6RbeITNCc {
            get {
                object obj = ResourceManager.GetObject("0p6RbeITNCc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1577779084_556198_294969 {
            get {
                object obj = ResourceManager.GetObject("1577779084-556198-294969", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1577779084_556198_294969_PhotoRoom_png_PhotoRoom {
            get {
                object obj = ResourceManager.GetObject("1577779084-556198-294969-PhotoRoom.png-PhotoRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1577779084_556198_294969_PhotoRoom1 {
            get {
                object obj = ResourceManager.GetObject("1577779084-556198-294969-PhotoRoom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1614546318_22_p_avto_na_belom_fone_25 {
            get {
                object obj = ResourceManager.GetObject("1614546318_22-p-avto-na-belom-fone-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1619655725_9_phonoteka_org_p_fon_cherno_zelenii_gradient_10 {
            get {
                object obj = ResourceManager.GetObject("1619655725_9-phonoteka_org-p-fon-cherno-zelenii-gradient-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1663658496_1_phonoteka_org_p_fon_krasno_zelenii_vkontakte_1 {
            get {
                object obj = ResourceManager.GetObject("1663658496_1-phonoteka-org-p-fon-krasno-zelenii-vkontakte-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1667316701_5_celes_club_p_krasivii_gradientnii_fon_vkontakte_7 {
            get {
                object obj = ResourceManager.GetObject("1667316701_5-celes-club-p-krasivii-gradientnii-fon-vkontakte-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1667316701_5_celes_club_p_krasivii_gradientnii_fon_vkontakte_71 {
            get {
                object obj = ResourceManager.GetObject("1667316701_5-celes-club-p-krasivii-gradientnii-fon-vkontakte-71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2019_02_15_16_23_07 {
            get {
                object obj = ResourceManager.GetObject("2019-02-15_16-23-07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8k3tjjmprry4q3jtp5s0yz67uqmt420a {
            get {
                object obj = ResourceManager.GetObject("8k3tjjmprry4q3jtp5s0yz67uqmt420a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8k3tjjmprry4q3jtp5s0yz67uqmt420a1 {
            get {
                object obj = ResourceManager.GetObject("8k3tjjmprry4q3jtp5s0yz67uqmt420a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Account_Login_Button_PNG_File {
            get {
                object obj = ResourceManager.GetObject("Account-Login-Button-PNG-File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Account_Login_Button_PNG_File1 {
            get {
                object obj = ResourceManager.GetObject("Account-Login-Button-PNG-File1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Account_Login_Button_PNG_File2 {
            get {
                object obj = ResourceManager.GetObject("Account-Login-Button-PNG-File2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap futuristic_car_fon_futuresynth_outrun_vid_sboku_neon_mashina {
            get {
                object obj = ResourceManager.GetObject("futuristic-car-fon-futuresynth-outrun-vid-sboku-neon-mashina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hochesh_delat_manikjur_na_professionalnom_urovne_i_imet_vozmozhnost_zarabotat_2_PhotoRoom_png_PhotoRoom {
            get {
                object obj = ResourceManager.GetObject("hochesh-delat-manikjur-na-professionalnom-urovne-i-imet-vozmozhnost-zarabotat-2-P" +
                        "hotoRoom.png-PhotoRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercedes_PNG80143 {
            get {
                object obj = ResourceManager.GetObject("mercedes_PNG80143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oboitut_com_1569435452 {
            get {
                object obj = ResourceManager.GetObject("oboitut.com_1569435452", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_car_car_trolley {
            get {
                object obj = ResourceManager.GetObject("png-clipart-car-car-trolley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_india_company_business_chief_executive_profile_building_company_PhotoRoom_png_PhotoRoom {
            get {
                object obj = ResourceManager.GetObject("png-clipart-india-company-business-chief-executive-profile-building-company-Photo" +
                        "Room.png-PhotoRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_teplogidrostroy_password_manager_admin_icon_data_teplogidrostroy_PhotoRoom_png_PhotoRoom {
            get {
                object obj = ResourceManager.GetObject("png-clipart-teplogidrostroy-password-manager-admin-icon-data-teplogidrostroy-Phot" +
                        "oRoom.png-PhotoRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_truck_wreck_antique_oldtimer_scrap_rusted_vintage_car_automobile_old_metal_classic {
            get {
                object obj = ResourceManager.GetObject("png-transparent-truck-wreck-antique-oldtimer-scrap-rusted-vintage-car-automobile-" +
                        "old-metal-classic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
